//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="HttpEndPointBinding", Namespace="http://www.ercot.com/wsdl/2007-06/nodal/ewsConcrete")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributedString))]
public partial class NodalService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback MarketTransactionsOperationCompleted;
    
    private System.Threading.SendOrPostCallback AlertsOperationCompleted;
    
    private System.Threading.SendOrPostCallback MarketInfoOperationCompleted;
    
    /// <remarks/>
    public NodalService() {
        this.Url = "https://misapi.ercot.com/2007-08/Nodal/eEDS/EWS/";
    }
    
    /// <remarks/>
    public event MarketTransactionsCompletedEventHandler MarketTransactionsCompleted;
    
    /// <remarks/>
    public event AlertsCompletedEventHandler AlertsCompleted;
    
    /// <remarks/>
    public event MarketInfoCompletedEventHandler MarketInfoCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("/BusinessService/NodalService.serviceagent/HttpEndPoint/MarketTransactions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("ResponseMessage", Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
    public ResponseMessage MarketTransactions([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")] RequestMessage RequestMessage) {
        object[] results = this.Invoke("MarketTransactions", new object[] {
                    RequestMessage});
        return ((ResponseMessage)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginMarketTransactions(RequestMessage RequestMessage, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("MarketTransactions", new object[] {
                    RequestMessage}, callback, asyncState);
    }
    
    /// <remarks/>
    public ResponseMessage EndMarketTransactions(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ResponseMessage)(results[0]));
    }
    
    /// <remarks/>
    public void MarketTransactionsAsync(RequestMessage RequestMessage) {
        this.MarketTransactionsAsync(RequestMessage, null);
    }
    
    /// <remarks/>
    public void MarketTransactionsAsync(RequestMessage RequestMessage, object userState) {
        if ((this.MarketTransactionsOperationCompleted == null)) {
            this.MarketTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarketTransactionsOperationCompleted);
        }
        this.InvokeAsync("MarketTransactions", new object[] {
                    RequestMessage}, this.MarketTransactionsOperationCompleted, userState);
    }
    
    private void OnMarketTransactionsOperationCompleted(object arg) {
        if ((this.MarketTransactionsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.MarketTransactionsCompleted(this, new MarketTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("/BusinessService/NodalService.serviceagent/HttpEndPoint/Alerts", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("ResponseMessage", Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
    public ResponseMessage Alerts([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")] RequestMessage RequestMessage) {
        object[] results = this.Invoke("Alerts", new object[] {
                    RequestMessage});
        return ((ResponseMessage)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAlerts(RequestMessage RequestMessage, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Alerts", new object[] {
                    RequestMessage}, callback, asyncState);
    }
    
    /// <remarks/>
    public ResponseMessage EndAlerts(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ResponseMessage)(results[0]));
    }
    
    /// <remarks/>
    public void AlertsAsync(RequestMessage RequestMessage) {
        this.AlertsAsync(RequestMessage, null);
    }
    
    /// <remarks/>
    public void AlertsAsync(RequestMessage RequestMessage, object userState) {
        if ((this.AlertsOperationCompleted == null)) {
            this.AlertsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlertsOperationCompleted);
        }
        this.InvokeAsync("Alerts", new object[] {
                    RequestMessage}, this.AlertsOperationCompleted, userState);
    }
    
    private void OnAlertsOperationCompleted(object arg) {
        if ((this.AlertsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AlertsCompleted(this, new AlertsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("/BusinessService/NodalService.serviceagent/HttpEndPoint/MarketInfo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("ResponseMessage", Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
    public ResponseMessage MarketInfo([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")] RequestMessage RequestMessage) {
        object[] results = this.Invoke("MarketInfo", new object[] {
                    RequestMessage});
        return ((ResponseMessage)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginMarketInfo(RequestMessage RequestMessage, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("MarketInfo", new object[] {
                    RequestMessage}, callback, asyncState);
    }
    
    /// <remarks/>
    public ResponseMessage EndMarketInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ResponseMessage)(results[0]));
    }
    
    /// <remarks/>
    public void MarketInfoAsync(RequestMessage RequestMessage) {
        this.MarketInfoAsync(RequestMessage, null);
    }
    
    /// <remarks/>
    public void MarketInfoAsync(RequestMessage RequestMessage, object userState) {
        if ((this.MarketInfoOperationCompleted == null)) {
            this.MarketInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarketInfoOperationCompleted);
        }
        this.InvokeAsync("MarketInfo", new object[] {
                    RequestMessage}, this.MarketInfoOperationCompleted, userState);
    }
    
    private void OnMarketInfoOperationCompleted(object arg) {
        if ((this.MarketInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.MarketInfoCompleted(this, new MarketInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
public partial class RequestMessage {
    
    private HeaderType headerField;
    
    private RequestType requestField;
    
    private PayloadType payloadField;
    
    /// <remarks/>
    public HeaderType Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    public RequestType Request {
        get {
            return this.requestField;
        }
        set {
            this.requestField = value;
        }
    }
    
    /// <remarks/>
    public PayloadType Payload {
        get {
            return this.payloadField;
        }
        set {
            this.payloadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
public partial class HeaderType {
    
    private HeaderTypeVerb verbField;
    
    private string nounField;
    
    private ReplayDetectionType replayDetectionField;
    
    private string revisionField;
    
    private string sourceField;
    
    private string userIDField;
    
    private string messageIDField;
    
    private string commentField;
    
    private System.Xml.XmlElement[] anyField;
    
    public HeaderType() {
        this.verbField = HeaderTypeVerb.get;
        this.revisionField = "001";
    }
    
    /// <remarks/>
    public HeaderTypeVerb Verb {
        get {
            return this.verbField;
        }
        set {
            this.verbField = value;
        }
    }
    
    /// <remarks/>
    public string Noun {
        get {
            return this.nounField;
        }
        set {
            this.nounField = value;
        }
    }
    
    /// <remarks/>
    public ReplayDetectionType ReplayDetection {
        get {
            return this.replayDetectionField;
        }
        set {
            this.replayDetectionField = value;
        }
    }
    
    /// <remarks/>
    public string Revision {
        get {
            return this.revisionField;
        }
        set {
            this.revisionField = value;
        }
    }
    
    /// <remarks/>
    public string Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public string UserID {
        get {
            return this.userIDField;
        }
        set {
            this.userIDField = value;
        }
    }
    
    /// <remarks/>
    public string MessageID {
        get {
            return this.messageIDField;
        }
        set {
            this.messageIDField = value;
        }
    }
    
    /// <remarks/>
    public string Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
public enum HeaderTypeVerb {
    
    /// <remarks/>
    cancel,
    
    /// <remarks/>
    canceled,
    
    /// <remarks/>
    change,
    
    /// <remarks/>
    changed,
    
    /// <remarks/>
    create,
    
    /// <remarks/>
    created,
    
    /// <remarks/>
    close,
    
    /// <remarks/>
    closed,
    
    /// <remarks/>
    delete,
    
    /// <remarks/>
    deleted,
    
    /// <remarks/>
    get,
    
    /// <remarks/>
    reply,
    
    /// <remarks/>
    submit,
    
    /// <remarks/>
    update,
    
    /// <remarks/>
    updated,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
public partial class ReplayDetectionType {
    
    private EncodedString nonceField;
    
    private AttributedDateTime createdField;
    
    /// <remarks/>
    public EncodedString Nonce {
        get {
            return this.nonceField;
        }
        set {
            this.nonceField = value;
        }
    }
    
    /// <remarks/>
    public AttributedDateTime Created {
        get {
            return this.createdField;
        }
        set {
            this.createdField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyIdentifierType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BinarySecurityTokenType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0" +
    ".xsd")]
public partial class EncodedString : AttributedString {
    
    private string encodingTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string EncodingType {
        get {
            return this.encodingTypeField;
        }
        set {
            this.encodingTypeField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(EncodedString))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyIdentifierType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BinarySecurityTokenType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PasswordString))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0" +
    ".xsd")]
public partial class AttributedString {
    
    private string idField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1." +
        "0.xsd", DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
public partial class ReplyType {
    
    private string replyCodeField;
    
    private string[] errorField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string[] idField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    public string ReplyCode {
        get {
            return this.replyCodeField;
        }
        set {
            this.replyCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Error")]
    public string[] Error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ID")]
    public string[] ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
public partial class PayloadType {
    
    private object[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    private string formatField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("Compressed", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Document", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    public string format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message", IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    Compressed,
    
    /// <remarks/>
    Document,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
public partial class RequestType {
    
    private RequestTypeMarketType marketTypeField;
    
    private bool marketTypeFieldSpecified;
    
    private System.DateTime operatingDateField;
    
    private bool operatingDateFieldSpecified;
    
    private System.DateTime tradingDateField;
    
    private bool tradingDateFieldSpecified;
    
    private System.DateTime startTimeField;
    
    private bool startTimeFieldSpecified;
    
    private System.DateTime endTimeField;
    
    private bool endTimeFieldSpecified;
    
    private string zoneField;
    
    private string aSTypeField;
    
    private string optionField;
    
    private string sortByField;
    
    private string[] idField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    public RequestTypeMarketType MarketType {
        get {
            return this.marketTypeField;
        }
        set {
            this.marketTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MarketTypeSpecified {
        get {
            return this.marketTypeFieldSpecified;
        }
        set {
            this.marketTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime OperatingDate {
        get {
            return this.operatingDateField;
        }
        set {
            this.operatingDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OperatingDateSpecified {
        get {
            return this.operatingDateFieldSpecified;
        }
        set {
            this.operatingDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime TradingDate {
        get {
            return this.tradingDateField;
        }
        set {
            this.tradingDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TradingDateSpecified {
        get {
            return this.tradingDateFieldSpecified;
        }
        set {
            this.tradingDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime StartTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StartTimeSpecified {
        get {
            return this.startTimeFieldSpecified;
        }
        set {
            this.startTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime EndTime {
        get {
            return this.endTimeField;
        }
        set {
            this.endTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EndTimeSpecified {
        get {
            return this.endTimeFieldSpecified;
        }
        set {
            this.endTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Zone {
        get {
            return this.zoneField;
        }
        set {
            this.zoneField = value;
        }
    }
    
    /// <remarks/>
    public string ASType {
        get {
            return this.aSTypeField;
        }
        set {
            this.aSTypeField = value;
        }
    }
    
    /// <remarks/>
    public string Option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    public string SortBy {
        get {
            return this.sortByField;
        }
        set {
            this.sortByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ID")]
    public string[] ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
public enum RequestTypeMarketType {
    
    /// <remarks/>
    DAM,
    
    /// <remarks/>
    RTM,
    
    /// <remarks/>
    SASM,
    
    /// <remarks/>
    HRUC,
    
    /// <remarks/>
    DRUC,
    
    /// <remarks/>
    SCED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1." +
    "0.xsd")]
public partial class AttributedDateTime {
    
    private string idField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0" +
    ".xsd")]
public partial class PasswordString : AttributedString {
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0" +
    ".xsd")]
public partial class KeyIdentifierType : EncodedString {
    
    private string valueTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string ValueType {
        get {
            return this.valueTypeField;
        }
        set {
            this.valueTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0" +
    ".xsd")]
public partial class BinarySecurityTokenType : EncodedString {
    
    private string valueTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string ValueType {
        get {
            return this.valueTypeField;
        }
        set {
            this.valueTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
public partial class ResponseMessage {
    
    private HeaderType headerField;
    
    private ReplyType replyField;
    
    private PayloadType payloadField;
    
    /// <remarks/>
    public HeaderType Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    public ReplyType Reply {
        get {
            return this.replyField;
        }
        set {
            this.replyField = value;
        }
    }
    
    /// <remarks/>
    public PayloadType Payload {
        get {
            return this.payloadField;
        }
        set {
            this.payloadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void MarketTransactionsCompletedEventHandler(object sender, MarketTransactionsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MarketTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal MarketTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ResponseMessage Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ResponseMessage)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void AlertsCompletedEventHandler(object sender, AlertsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AlertsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal AlertsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ResponseMessage Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ResponseMessage)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void MarketInfoCompletedEventHandler(object sender, MarketInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MarketInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal MarketInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ResponseMessage Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ResponseMessage)(this.results[0]));
        }
    }
}
